/**
 * The owner's escape hatch for a computed column that shipped stale or missing.
 *
 * `src/db/schema.ts`'s own section comment draws the line this module enforces: the
 * "Computed facts" tables are rebuilt idempotently from Actual, Ghostfolio and the
 * settings the owner has already chosen, and nothing here is judgement. Every other
 * table — `category_meta`, `account_map`, `settings`, the AI ledger — is either
 * configuration or a record that cannot be regenerated, and none of it is touched.
 *
 * The AI tables are the one case worth spelling out. They look "generated by
 * Balancr" the same way a signal does, but `ai_spend_monthly` sums `ai_runs`
 * unconditionally to answer "how much has this month already cost" — deleting that
 * ledger would make the budget guard think less was spent than actually was, which
 * is a real overspend risk rather than a stale figure. So they stay out.
 */
import type { Db } from '../../db/index.ts'
import {
  categoryGuessCandidates,
  monthlyCategoryFacts,
  monthlyHygiene,
  monthlySignals,
  monthlyTotals,
  netWorthSnapshots,
  portfolioMetrics,
  portfolioSnapshots,
  recomputeMismatches,
} from '../../db/schema.ts'

export interface ResetResult {
  table: string
  rows: number
}

/**
 * Every table this deletes from, and the name each answer carries.
 *
 * A list rather than nine separate statements written out, so the audit entry and
 * the one test asserting "exactly these tables" both read from the same source
 * instead of three copies that could each drift from the schema's own section on
 * their own.
 */
const COMPUTED_TABLES = [
  { name: 'monthly_category_facts', table: monthlyCategoryFacts },
  { name: 'monthly_totals', table: monthlyTotals },
  { name: 'recompute_mismatches', table: recomputeMismatches },
  { name: 'monthly_hygiene', table: monthlyHygiene },
  { name: 'monthly_signals', table: monthlySignals },
  { name: 'category_guess_candidates', table: categoryGuessCandidates },
  { name: 'net_worth_snapshots', table: netWorthSnapshots },
  { name: 'portfolio_snapshots', table: portfolioSnapshots },
  { name: 'portfolio_metrics', table: portfolioMetrics },
] as const

/**
 * Wipes every computed-fact table, in one transaction so a reader never sees the
 * database half-emptied.
 *
 * Returns the count from each table, which is what the caller's audit entry
 * records as `before` — "how much was there" is the only useful trail for an
 * operation whose whole point is that none of it survives.
 */
export function resetComputedData(db: Db): ResetResult[] {
  return db.transaction((tx) =>
    COMPUTED_TABLES.map(({ name, table }) => ({
      table: name,
      rows: tx.delete(table).run().changes,
    })),
  )
}
